services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/cottages-app

    command: >
      sh -c  "./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
    container_name: cottages_celery
    command: >
      sh -c "celery -A core worker -l INFO"
    depends_on:
      - redis